routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\productController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentController;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductAdminController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SellerController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VeroController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//0 = superadmin 1=admin 2=lister 3=riset
// Route::get("/admin/product",[productController::class, 'index'])->name("admin.product");
Route::get('/', [UserController::class, 'login']);
Route::get('/admin', [UserController::class, 'login'])->name('admin.login');
Route::post('/user/login', [UserController::class, 'aksi']);

Route::middleware(['guest'])->group(function()
{
});
Auth::routes();
Route::middleware(['auth'])->group(function()
{   
    Route::get("admin/home",[HomeController::class, 'Home'])->name("home");
    Route::get('user', [UserController::class, 'list_user'])->name('user');
    Route::get('user/register', [UserController::class, 'add_user'])->name('user.add');
    Route::post('user/adduser', [UserController::class, 'adduser'])->name('user.adduser');
    Route::post('/check_asin', [productController::class, 'checkAsin'])->name('check_asin');
    Route::post('/check_brand', [productController::class, 'checkBrand'])->name('check_brand');
    
    Route::resource('ProductList', productController::class);
    Route::resource('filter_akun', productController::class);
    Route::controller(productController::class)->prefix('product')->group(function () {
    Route::get('edit/{id}', 'edit')->name('barang.edit');
    Route::post('listing', 'listing')->name('barang.listing'); 
       
    });
    Route::get('admin/product',[productController::class,'index'])->name("product");
    Route::get('product/filter_akun', [productController::class, 'search_account'])->name('product.search_account');    
    Route::get('product/removeall', [productController::class, 'removeall'])->name('product.removeall');   
    Route::get('product/list_item',[productController::class, 'list_item']); 
    Route::get('/product/create', function () { return view('product.create');});

    Route::get('/vero',[VeroController::class, 'index'])->name("vero");
    Route::get('/vero/add_vero',[VeroController::class, 'add_vero'])->name('vero.add_vero');
    Route::post('/vero/addvero',[VeroController::class, 'addvero'])->name('vero.addvero');
    Route::post('/vero/addasinvero',[VeroController::class, 'addasinvero'])->name('vero.addasinvero');
    Route::post('/vero/addbrandvero',[VeroController::class, 'addbrandvero'])->name('vero.addbrandvero');
    Route::post('/vero/addjudulvero',[VeroController::class, 'addjudulvero'])->name('vero.addjudulvero');
    Route::post('/vero/addKeywordvero',[VeroController::class, 'addKeywordvero'])->name('vero.addKeywordvero');
    Route::post('/vero/import',[VeroController::class, 'import'])->name('vero.import');
    Route::get('/vero/edit/{id}',[VeroController::class, 'edit'])->name('vero.edit');
    Route::post('/vero/update/{id}',[VeroController::class, 'update'])->name('vero.update');
    Route::get('/vero/delete/{id}',[VeroController::class, 'delete'])->name('vero.delete');
    Route::post('/vero/destroy',[VeroController::class, 'destroy'])->name('vero.destroy');

    Route::get('/seller', [SellerController::class, 'index'])->name('seller');
    Route::get('/seller/add_seller',[SellerController::class, 'add_seller'])->name('seller.add_seller');
    Route::post('/seller/addseller',[SellerController::class, 'addseller'])->name('seller.addseller');
    Route::get('/seller/edit/{id}', [SellerController::class, 'edit'])->name('seller.edit');
    Route::post('/seller/update/{id}', [SellerController::class, 'update'])->name('seller.update');
    Route::get('/seller/list_seller',[SellerController::class,'list_seller'])->name('seller.list_seller');
    Route::resource('/seller/addseller', SellerController::class);

    
    Route::get('/account',[AccountController::class, 'index'])->name("accounts");
    Route::get('/accounts/add_accs',[AccountController::class, 'create'])->name('accounts.add_accs');
    Route::get('/accounts/edit/{id}',[AccountController::class, 'edit'])->name('accounts.edit');
    Route::post('/accounts/addacc',[AccountController::class, 'store'])->name('accounts.addacc');
    Route::post('/accounts/update/{id}', [AccountController::class, 'update'])->name('accounts.update');

    Route::get('/report', [ReportController::class, 'index'])->name('report');
    Route::get('/report/count', [ReportController::class, 'countBarang'])->name('report.countBarang');
    Route::get('/report/countlisting', [ReportController::class, 'countlisting'])->name('report.countlisting');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class product extends Model
{
    use HasFactory;
    public $table = "tb_product";
    protected $fillable = ['asin','judul','harga','brand','image','judul_eb','harga_eb','account_ebay','penginput','penginput_id'];
   public function user()
    {
        return $this->belongsTo(User::class, 'penginput_id');
    }
    
    
}

app/Http/Controllers/productController.php
<?php

namespace App\Http\Controllers;

use App\Models\Account;
use DateTime;
use App\Models\product;
use App\Models\Vero;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;

class productController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $account = Account::where('lister', auth()->user()->name)->get();
        return view('product.index',['account'=>$account]);
    }
    public function list_item(Request $request)
    {
        
        if ($request->ajax()) {
            if ($request->account_ebay != null) {
                $data = Product::where('account_ebay', $request->account_ebay)->get();
            } else if (auth()->user()->role == 'lister') {
                $data = Product::where(function($query) {
                    $query->whereHas('user', function ($subquery) {
                        $subquery->where('role', '=', 'admin');
                    })->orWhere('penginput', '=', auth()->user()->name);
                })->orderby('account_ebay','ASC')->get();
            } else if (auth()->user()->role == 'superadmin') {
                $data = Product::orderBy('account_ebay', 'asc')->latest()->get();
            }
           
         return Datatables::of($data)
                ->addColumn('checkbox', function ($data) {
                    if ($data->account_ebay !== null) {
                        return '';
                    } 
                    return '<input type="checkbox" name="product_checkbox[]" class="product_checkbox" value="'.$data->id.'" />';
                })
                ->addIndexColumn()
                ->addColumn('action', function ($data) {
                    return '<a href="https://amazon.com/dp/'.$data->asin.'" target="_blank">'.$data->asin.'</a><br>';
                })
                ->addColumn('title', function ($data) {
                    return '<div class="pd-5" style="font-size: 15px;"><b>Judul Amazon : </b>'.$data->judul.'</div><br><b>Judul eBay :</b><br>'.Str::limit($data->judul_eb, 80);
                })
                ->addColumn('price', function ($data) {
                    return '<div class="pd-5" style="font-size: 15px;"> <img src="'.asset('img/315-3159325_amazon.png').'" class="mb-3" width=35px><br>$'.$data->harga.'</div><br><img src="'.asset('img/143967.png').'" class="mb-3" width=45px> <br>$'.$data->harga_eb;
                })
                ->addColumn('penginput_barang', function($data){
                    return '<div style="text-align: center;">' . $data->penginput . '</div><br><div style="text-align: center;">' . \Carbon\Carbon::parse($data->created_at)->format('d-M-Y') . '<br><div style="text-align: center;">' . \Carbon\Carbon::parse($data->created_at)->format('h:i A').'</div>';
                })
                ->addColumn('penginput_barang', function($data){
                    return '<div style="text-align: center;">' . $data->penginput . '</div><br><div style="text-align: center;">' . \Carbon\Carbon::parse($data->created_at)->format('d-M-Y') . '<br><div style="text-align: center;">' . \Carbon\Carbon::parse($data->created_at)->format('h:i A').'</div>';
                })
                ->addColumn('listing', function ($data) {
                    return $data->account_ebay>0? view('product.column')->with('data', $data):"";
                })
                
                ->addColumn('aksi', function ($data) {
                    $image = asset($data->image);
                    return '<div style="display: flex; justify-content: center; align-items: center; height: 100%;"><img src="'.$image.'" alt="Image" width="100px"></div><p style="text-align: center;"><button type="button" class="btn btn-outline-primary mt-3">Brand: '.$data->brand.'</button></p>';
                })
                ->rawColumns(['checkbox','aksi','title','price','penginput_barang','listing','action'])
                ->make(true);
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search_account(Request $request)
    {
        $output ="";
        $account = $request->search_acc;
        $listingBanyak = product::whereIn('account_ebay', $account)->get();
        
        return response($output);
    }
    public function create()
    {  
       
       return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validasi = Validator::make($request->all(), [
            'asin' => 'required|unique:tb_product,asin|unique:tb_vero,asin',
            'judul' => 'required',
            'harga' => 'required',
            'image_url' => 'required',
            'brand' => 'required|unique:tb_vero,brand',
        ], [
            'asin.required' => 'Asin wajib diisi',
            'asin.unique' => 'Asin Sudah ada, silakan ganti Asin anda',
            'judul.required' => 'Judul wajib diisi',
            'harga.required' => 'Harga wajib diisi',
            'brand.required' => 'Brand wajib diisi',
            'image_url.required' => 'Link Gambar wajib diisi',
            'brand.unique' =>'Tidak boleh memasukan Brand ini',
        ]);

        if ($validasi->fails()) {
            return redirect('ProductList/create')
                        ->withErrors($validasi)
                        ->withInput();
        } else {
           
            // Retrieve an array of words from another table
            $words_to_remove = Vero::get('keyword')->pluck('keyword')->toArray();
            $title = $request->judul_eb;
            $title_correction =str::replace($words_to_remove,[''], $title);

            // Create the data array to insert into the table
            $data = [
                'asin' => $request->asin,
                'judul' => $request->judul,
                'harga' => $request->harga,
                'brand' => $request->brand,
                'image' => $request->image_url,
                'judul_eb' => $title_correction,
                'harga_eb' => $request->harga_eb,
                'penginput' => $request->penginput,
                'penginput_id' => auth()->user()->id
            ];

            // Insert data into the table
            product::create($data);

            return redirect()->route('ProductList.create')->with('success','Produk berhasil disimpan.');
        }
    }
    public function getProduct()
    {
        
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
	{
		$barang = product::find($id)->first();

		return view('product.edit', ['barang' => $barang]);
	}
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = product::findOrFail($id);
        $data->delete();
    }
    function removeall(Request $request)
    {
        $user_id_array = $request->input('id');
        $user = product::whereIn('id', $user_id_array);
        if($user->delete())
        {
            echo 'Data Deleted';
        }
    }
   function listing(Request $request)
    {
        
        $item_array = $request->input('id');
        $item_list = $request->input('account_ebay');
        $lister = $request->input('lister');
        $listingBanyak = product::whereIn('id', $item_array);
        foreach ($item_array as $key){
            $data = array(
                'account_ebay' => $item_list,
                'lister' => $lister,
                'listed_at' => Carbon::now()
            );
            $listingBanyak->update($data, $key);
            return response()->json(['success' => "Barang Berhasil di listing"]);
        }
        

    }
    public function checkAsin(Request $request)
    {
        $asin = $request->input('asin');

        if(!empty($asin)) {
            $cek_asin = product::where('asin', $asin)->count();
            $cek_asinvero = Vero::where('asin', $asin)->count();
            if($cek_asin > 0){
                return '<div class="text-red alert alert-danger" style="padding: 7px;padding-left: 17px;">Asin sudah ada, silahkan ganti dengan yang lain</div>';
            }elseif($cek_asinvero >0){
                return '<div class="text-red alert alert-danger" style="padding: 7px;padding-left: 17px;"><i class="fas fa-fw fa-exclamation-triangle"></i> Asin masuk list vero, silahkan ganti dengan yang lain</div>';
            }else {
                return '<div class="text-green alert alert-success" style="padding: 7px;padding-left: 17px;">ASIN Tersedia dan aman</div>';
            } 
        } else {
            return "";
        }
    }
    public function checkBrand(Request $request)
    {
        $brand = $request->input('brand');

        if(!empty($brand)) {
            $cek_brandVero = Vero::where('brand', $brand)->count();
            if($cek_brandVero >0){

resources/views/product/column.blade.php
@if($data->lister!==null)
  <div style="text-align: center;"  class="mb-3">
  <div margin: 0 auto;>{{$data->lister}}</div>
</div>
@elseif($data->listed_at!==null)
<div style="text-align: center;"  class="mb-5">
  <div margin: 0 auto;>{{date('d-M-Y', strtotime($data->listed_at))}}</div>
  <div margin: 0 auto;>{{date('h:i A', strtotime($data->listed_at))}}</div>
</div>

@endif
<div style="text-align: center;">
    <div margin: 0 auto;>{{$data->account_ebay}}</div>
  </div>
<div style="text-align: center;">
    <div margin: 0 auto;>{{date('d-M-Y', strtotime($data->updated_at))}}</div>
    <div margin: 0 auto;>{{date('h:i A', strtotime($data->updated_at))}}</div>
</div>

resources/views/product/create.blade.php
@extends('layout.template')
<!-- End of Topbar -->
@section('isi')
               
               <!-- Begin Page Content -->
               <div class="container-fluid">

                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">Input Data Barang</h1>
                <p class="mb-4">Data barang hanya diperbolehkan dengan harga amazon minimal $4.99, dan selisih dengan kompetitor maksimal $5.99.</p>                  
                <!-- DataTales Example -->


                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary"> <a href='{{url('admin/product')}}' class="btn btn-warning">+ Kembali</a></h6>
                    </div>
                    
                    <div class="card-body">
                        <form action="{{ route('ProductList.store') }}" method="POST">
                            @csrf
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                        @endif
                      
                        <div class="mb-3 row">
                            <label for="asin" class="col-sm-2 col-form-label">ASIN</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" name='asin' id="asin"  onChange="checkProductCode()" value="{{old('asin')}}">
                                @error('asin')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-sm-4">
                                <span id="asin-status" ></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="brand" class="col-sm-2 col-form-label">BRAND / Merek</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" name='brand' id="brand"  onChange="checkBrand()" value="{{old('brand')}}">
                                @error('brand')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-sm-4">
                                <span id="brand-status" ></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="brand" class="col-sm-2 col-form-label">Link Gambar Produk</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" name='image_url' id="image_url" >
                                @error('image_url')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-sm-4">
                                <span id="brand-status" ></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="judul" class="col-sm-2 col-form-label">Judul Amazon</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name='judul' id="judul">
                                @error('judul')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="harga" class="col-sm-2 col-form-label">Harga</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" name='harga' id="harga" onkeyup="estBe()" onchange="estBe()">
                                @error('harga')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                            <label for="harga" class="col-form-label">Est. Sell ($)</label>
                            <div class="col-sm-2">
                                <div class="form-control" id="estSell" readonly></div>
                            </div>
                            <label for="harga" class="col-form-label">BE</label>
                            <div class="col-sm-1">
                                <div class="form-control" id="BeSell" readonly></div>
                            </div>
                                 
                        </div>
                        <div class="mb-3 row">
                            <label for="judul_eb" class="col-sm-2 col-form-label">Judul eBay</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name='judul_eb' id="judul_eb">
                                @error('judul_eb')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="harga_eb" class="col-sm-2 col-form-label">Harga </label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" name='harga_eb' id="harga_eb" onkeyup="Becomp()" onchange="Becomp()">
                                @error('harga_eb')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                            <label for="harga" class="col-form-label">BE Competitor (%)</label>
                            <div class="col-sm-1">
                                <div class="form-control" id="bEcomp" readonly></div>
                            </div>

                            <label for="harga" class="col-form-label">Selisih ($)</label>
                            <div class="col-sm-1">
                               <div class="form-control" id="selisih" readonly></div>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="harga_eb" class="col-sm-2 col-form-label">Penginput</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" name='penginput' id="penginput" value="{{ Auth::user()->name }}" readonly>
                                <input type="text" class="form-control" name='penginput_id' id="penginput_id" value="{{ Auth::user()->id }}" hidden>
                                @error('penginput')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                            
                        </div>
                        <button type="submit" id="btn-simpan" class="btn btn-primary ml-3">Submit</button>
                        </form>
                    </div>
                </div>
            </div>

                <!-- /.container-fluid -->
            <script>
              function checkProductCode(){
                var asin = $('#asin').val();
                $.ajax({
                  url:"{{ route('check_asin')}}",
                  headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                  method:"post",
                  data:{
                   
                    asin:asin
                },
                success:function(data)
                {
                    $("#asin-status").html(data);
                }
                   
                });
              };
              function checkBrand(){
                var brand = $('#brand').val();
                $.ajax({
                  url:"{{ route('check_brand')}}",
                  headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                  method:"post",
                  data:{
                   
                    brand:brand
                },
                success:function(data)
                {
                    $("#brand-status").html(data);
                }
                   
                });
              };
              function estBe() {
                var priceAz = $('#harga').val();
                var priceEb = $('#harga_eb').val();
                var set_profit = 0.5;
                var set_BeSell = 35;
                let est_sell = (parseFloat(priceAz) + parseFloat(set_profit)) * 100 / (100 - set_BeSell);
                document.getElementById("estSell").innerHTML = est_sell.toFixed(2);
                document.getElementById("BeSell").innerHTML = set_BeSell;
                var harga_sell = document.getElementById("BeSell").innerHTML;
                if(priceAz<=4.99){
                    $('#btn-simpan').prop('disabled', true);
                    } else {
                    $('#btn-simpan').prop('disabled', false);
                    }
                $.ajax({
                    url: "{{ route('ProductList.store') }}",
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    type: "POST",
                    data: { harga_sell: harga_sell },
                    success: function(response) {
                        console.log(response)
                    }
                });
            }

             function Becomp(){
                var priceAz = $('#harga').val();
                var priceEb = $('#harga_eb').val();
                var set_profit = 0.5;
                var set_BeSell = 35;
                var est_sell = (parseFloat(priceAz) + parseFloat(set_profit)) * 100 / (100 - set_BeSell);
                let est_beComp = 100*(parseFloat(priceEb) - parseFloat(priceAz)-set_profit)/parseFloat(priceEb);
                document.getElementById("bEcomp").innerHTML = est_beComp.toFixed();
                var harga_sell = document.getElementById("BeSell").innerHTML;

                var selisih = parseFloat(est_sell) - parseFloat(priceEb);
                document.getElementById("selisih").innerHTML = selisih.toFixed(2);
                var selisih_harga = document.getElementById("selisih").innerHTML;
                if (selisih_harga >= 5.99) {
                $('#btn-simpan').prop('disabled', true);
                } else {
                $('#btn-simpan').prop('disabled', false);
                }

             }


            </script>
@endsection

resources/views/product/edit.blade.php
@extends('layout.template')
@section('isi')
@extends('layout.template')
<!-- End of Topbar -->
@section('isi')
               
               <!-- Begin Page Content -->
               <div class="container-fluid">

                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">Tables</h1>
                <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                        href="https://datatables.net">official DataTables documentation</a>.</p>                  
                <!-- DataTales Example -->


                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary"> <a href='{{url('product')}}' class="btn btn-warning">+ Kembali</a></h6>
                    </div>
                    
                    <div class="card-body">
                        <form action="{{ route('ProductList.store') }}" method="POST">
                            @csrf
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                        @endif
                        <div class="mb-3 row">
                            <label for="nama" class="col-sm-2 col-form-label">ASIN :</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" name='asin' id="asin"  value="{{old('asin')}}">
                                @error('asin')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="email" class="col-sm-2 col-form-label">Judul :</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name='judul' id="judul">
                                @error('judul')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="email" class="col-sm-2 col-form-label">Harga :</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" name='harga' id="harga">
                                @error('harga')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary ml-3">Submit</button>
                        </form>
                    </div>
                </div>
            </div>

                <!-- /.container-fluid -->

@endsection

resources/views/product/tombol.blade.php
<a href='{{route('barang.edit',$data->id)}}' class="btn btn-warning btn-icon-split tombol-edit">
    <span class="icon text-white-5">
        <i class="fas fa-edit"></i>
    </span>
    <span class="text">Edit</span>
</a>
<a href='#' data-id="{{ $data->id }}" class="delete btn btn-danger btn-icon-split tombol-del"> 
<span class="icon text-white-5">
    <i class="fas fa-trash"></i>
</span>
<span class="text">Hapus</span></a>